//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electronics_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public string DeliveryCode { get; set; }
        public string DeliveryName { get; set; }
        public Nullable<decimal> PriceTotal { get; set; }
        public Nullable<decimal> DeliveryFee { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
